language: python
python:
  - '2.7'
env:
  global:
    # $TRANSIFEX_PASSWORD for oscar_bot (used in transifex.sh)
    secure: FuIlzEsGJiAwhaIRBmRNsq9eXmuzs25fX6BChknW4lDyVAySWMp0+Zps9Bd0JgfFYUG3Ip+OTmksYIoTUsG25ZJS9cq1IFt3QKUAN70YCI/4ZBLeIdICPEyxq+Km179+NeEXmBUug17RLMLxh3MWfO+RKUHK9yHIPNNpq0dNyoo=
  matrix:
    - DRF_VERSRION=">=2.3,<2.4" DJANGO_VERSION=">=1.4,<1.5"
    - DRF_VERSRION=">=2.3,<2.4" DJANGO_VERSION=">=1.5,<1.6"
    - DRF_VERSRION=">=2.3,<2.4" DJANGO_VERSION=">=1.6,<1.7"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install:
  - pip install wheel setuptools -U
  - pip install Django$DJANGO_VERSION djangorestframework$DRF_VERSION --use-wheel
  - pip install . --use-mirrors --use-wheel
  - pip install -r requirements.txt --use-mirrors --use-wheel
script:
  - make travis
after_success:
  - coveralls
  - ./transifex.sh
