language: python
python:
  - '2.7'
env:
  matrix:
    - DRF_VERSRION=">=2.3,<2.4" DJANGO_VERSION=">=1.4,<1.5"
    - DRF_VERSRION=">=2.3,<2.4" DJANGO_VERSION=">=1.5,<1.6"
    - DRF_VERSRION=">=2.3,<2.4" DJANGO_VERSION=">=1.6,<1.7"
  global:
    - secure: In7OAx5PDRnl+ajZIYHyIuAX1tI6pS0uIaHurFEVymB7c4Tl406ijatV8Gzv712wtctTr1g+plQfeH+NL0S/2N1MU3iG8Mu3t1HRkwsjwzeDH8qH2rNYLqpgDorWrNo9fw3OgPRNXtuFGtZSjgOdMYWBo5hADGMEtYsi5TqwOUM=
    - secure: lKXh3rCi8sseZ/OuXEMlTxahdDJJB6MVcgYu7MeiG/FpXNuV535zbzc3DK3Y1O6aJCqjyLZKX82vMCSrzVBw57QoZuQpgsIs2DsJQYmEdsti+3FQJzEjTdEsx+lcMP0MlaAEFiryTi6mTIlHRpwyJ5QMIpsfZYFsfMwS5rlP/7c=
install:
  - pip install wheel setuptools -U
  - pip install Django$DJANGO_VERSION djangorestframework$DRF_VERSION --use-wheel
  - pip install . --use-mirrors --use-wheel
  - pip install -r requirements.txt --use-mirrors --use-wheel
  - pip install -r requirements_oscar.txt --use-mirrors --use-wheel
  - npm -g install less
before_script:
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
script:
  - py.test --pep8
  - USE_OSCAR_SANDBOX=true py.test --pep8 --cov fancypages
  - py.test -m integration
after_success:
  - coveralls
